parameters:
#    czarnodziej_core.example.class: Czarnodziej\CoreBundle\Example

services:
#    czarnodziej_core.example:
#        class: %czarnodziej_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
