parameters:
#    czarnodziej_core.example.class: Czarnodziej\CoreBundle\Example

services:
    date_mod:
        class: Czarnodziej\CoreBundle\Dates\DateMod
#        name: date_mod
#        arguments: [@service_id, "plain_value", %parameter%]
