# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: true
#    bundles:        []
    #java: /usr/bin/java
    node: /usr/local/bin/node
    filters:
        cssrewrite: ~
#        cssimport: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        uglifyjs:
            #change according to NODE.js/NPM config
            bin: /home/marcin/npm/lib/node_modules/uglify-js/bin/uglifyjs
        uglifycss:
            #change according to NODE.js/NPM config
            bin: /home/marcin/npm/lib/node_modules/uglifycss/uglifycss
        jpegoptim:
            bin: /usr/bin/jpegoptim
            strip_all: true
            max: 50
        optipng:
            bin: /usr/bin/optipng

    assets:
        jquery:
            inputs:
                - %kernel.root_dir%/../web/components/jquery/jquery.js
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.css
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.js
        fontawesome_css:
            inputs:
                - %kernel.root_dir%/../web/components/fontawesome/css/font-awesome.css
            filters:
                - cssrewrite
            output: css/fontawesome.css
